In [1]:
import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath('../src'))

from sklearn.model_selection import train_test_split
from sklearn.base import clone
from DataLoader import DataLoader
from DataSplitter import DataSplitter
from PreProcessorML import PreProcessorML
from ModelCollection import ModelCollection
from PipelineML import PipelineML
from CrossValidation import CrossValidation

In [2]:
## Loading data
data_loader = DataLoader(path_train="../data/labeledTrainData.csv", path_test="../data/testData.csv")
data_splitter = DataSplitter(target_column="sentiment")
train, test = data_loader.load()
train.shape, test.shape

((25000, 3), (25000, 2))

In [3]:
train

            id  sentiment                                             review
0       5814_8          1  With all this stuff going down at the moment w...
1       2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2       7759_3          0  The film starts with a manager (Nicholas Bell)...
3       3630_4          0  It must be assumed that those who praised this...
4       9495_8          1  Superbly trashy and wondrously unpretentious 8...
...        ...        ...                                                ...
24995   3453_3          0  It seems like more consideration has gone into...
24996   5064_1          0  I don't believe they made this film. Completel...
24997  10905_3          0  Guy is a loser. Can't get girls, needs to buil...
24998  10194_3          0  This 30 minute documentary Buñuel made in the ...
24999   8478_8          1  I saw this movie as a child and it broke my he...

[25000 rows x 3 columns]

In [4]:
## splitting data
X, y = train.drop(columns=['sentiment']), train['sentiment']
X_train, X_test, y_train, y_test = data_splitter.split(train)
X_train.shape, X_test.shape, y_train.shape, y_test.shape, X_train.shape[0] / (X_test.shape[0] + X_train.shape[0])

((20000, 2), (5000, 2), (20000,), (5000,), 0.8)

In [5]:
## ML pipeline builder
pipeline_builder = PipelineML(train)

### Logistic Regression

In [6]:
params = {'l1_ratio': 0, 'solver': 'saga', 'C': 10.0, 'max_iter': 1000}
pipeline = pipeline_builder.build(model_name="Logistic Regression", params=params)
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nlp',
                                                  Pipeline(steps=[('cleaner',
                                                                   FunctionTransformer(func=<bound method PreProcessorML.clean of <PreProcessorML.PreProcessorML object at 0x00000214377AF3E0>>)),
                                                                  ('vectorizer',
                                                                   TfidfVectorizer(ngram_range=(1,
                                                                                                2),
                                                                                   token_pattern="(?u)\\b[\\w']+\\b"))]),
                                                  ['review'])])),
                ('model',
                 LogisticRegression(C=10.0, l1_ratio=0, max_iter=1000,
                                    solver='saga'))])

In [7]:
## Hold-Out Validation score (one fold only)
cv = CrossValidation(pipeline=clone(pipeline))

cv_score = cv.evaluate_one_fold(X_train, y_train, X_test, y_test)
print("Holdout Validation score: ", cv_score)

## K-fold Cross-Validation 
cv_score = cv.evaluate(X, y)
print("K-fold CV score: ", cv_score)

Fit time: 45.00470209121704
Prediction time: 4.932844877243042

Holdout Validation score:  0.905
K-fold CV score:  {'mean_rmse': np.float64(0.90504), 'std_rmse': np.float64(0.004068218283229162)}

In [10]:
## Hyper-parameter tunning
param_grid = {
    "model__C": [1e-4, 1e-2, 1, 10],
    "model__l1_ratio": [0],
}

cv_lg_results = cv.hyper_param_tune_one_fold(X_train, y_train, X_test, y_test, param_grid, 
                                             reduced=True, train_size=5000, return_loss_curves=False)
cv_lg_results

Params:  {'model__C': 0.0001, 'model__l1_ratio': 0}
Fit time: 15.014885663986206
Prediction time: 5.759066581726074

Params:  {'model__C': 0.01, 'model__l1_ratio': 0}
Fit time: 9.236612558364868
Prediction time: 4.923105478286743

Params:  {'model__C': 1, 'model__l1_ratio': 0}
Fit time: 8.662252426147461
Prediction time: 5.100586414337158

Params:  {'model__C': 10, 'model__l1_ratio': 0}
Fit time: 11.359908103942871
Prediction time: 4.772071838378906

Total CV time: 64.84625697135925

,model__C,model__l1_ratio,fit_time,pred_time,epochs,final_loss,final_validation_score,score
3,10.0000,0,11.359908,4.772072,NaN,NaN,NaN,0.8840
2,1.0000,0,8.662252,5.100586,NaN,NaN,NaN,0.8660
1,0.0100,0,9.236613,4.923105,NaN,NaN,NaN,0.7914
0,0.0001,0,15.014886,5.759067,NaN,NaN,NaN,0.4962

In [11]:
## Create submission using best hyper-parameters
preds = cv.pipeline.fit(X, y).predict(test)
submission = pd.DataFrame({"id": test['id'], "sentiment": preds})
submission.to_csv("../data/submission_lg.csv", index=False)